sudo: false

language: python

python:
- "3.4"
- "3.5"

cache:
  directories:
  - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt

script:
- py.test tests.py
